// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MewPipe.Logic.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddedScopeToAccessToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedScopeToAccessToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201501302235520_AddedScopeToAccessToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
